repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  # Git state
  - id: check-merge-conflict
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  # Sensitive information
  - id: detect-private-key
    stages: [commit]
  # Generic file state
  - id: trailing-whitespace
    stages: [commit]
  - id: mixed-line-ending
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
    exclude: .*\.tfvars$ # terraform fmt separates everything with blank lines leaving a trailing line at the end
  - id: check-yaml
    args: [--allow-multiple-documents]
    stages: [commit]
- repo: https://github.com/thlorenz/doctoc
  rev: v2.0.0
  hooks:
  - id: doctoc
- repo: https://github.com/jmmirand/my-own-precommit
  rev: v1.0.8
  hooks:
  - id: md-toc
    args:
      - ./doc/actions-runner-controller-arm.md
      - ./doc/docker-compose-runner.md
      - ./doc/docker-runner.md
      - ./doc/docker-swarm-runners.md
    pass_filenames: false
