name: Build gha runner

on: push

jobs:
  build_and_push:
    name: Push Docker image to multiple arch in registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

# https://github.com/multiarch/qemu-user-static
# https://github.com/docker/buildx/issues/495
#      - name: Print docker arquitectures
#        run: |
#          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#          docker buildx create --name multiarch --driver docker-container --use
#          docker buildx inspect --bootstrap
#          docker buildx ls
#          docker buildx build --platform linux/arm64 -t user/repo --no-cache --pull .
#          docker buildx build --push --platform linux/amd64,linux/arm64 .
      - name: Latest runner version
        shell: bash
        run: |
          export RUNNER_VERSION=$(curl  --silent "https://api.github.com/repos/actions/runner/releases/latest" | grep "tag_name" | sed -E 's/.*"v([^"]+)".*/\1/')
          echo "::set-output name=runner_version::${RUNNER_VERSION}"
        id: extract_branch_name


      - name: Build & Push to Docker Hub amd64(x86)
        uses: docker/build-push-action@v2
        with:
         # context: ./docker-runner
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: jmmirand/gha-docker-runner:${{ steps.extract_branch_name.outputs.runner_version }}
          push: true
          build-args: |
            RUNNER_VERSION=${{ steps.extract_branch_name.outputs.runner_version }}
