name: Build gha runner

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

jobs:
  build_and_push:
    name: Push Docker image to multiple arch in registry
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files




      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build & Push to Docker Hub amd64/arm
        uses: docker/build-push-action@v2
        with:
         # context: ./docker-runner
          file: ./Dockerfile
          platforms: linux/arm/v7
          tags: jmmirand/gha-docker-runner
          push: true
