name: Shared Docker Build

on: [push]

jobs:
  runs-on: ubuntu-latest
  build-docker-image:
    steps:  
      - name: Latest runner version
        shell: bash
        run: |
          export RUNNER_VERSION=$(curl  --silent "https://api.github.com/repos/actions/runner/releases/latest" | grep "tag_name" | sed -E 's/.*"v([^"]+)".*/\1/')
          echo "::set-output name=runner_version::${RUNNER_VERSION}"
        id: extract_branch_name

