name: Shared Docker Build

on: [push]

jobs:

  build-docker-prepare:
    runs-on: ubuntu-latest
    steps:  
      - name: Latest runner version
        shell: bash
        run: |
          export RUNNER_VERSION=$(curl  --silent "https://api.github.com/repos/actions/runner/releases/latest" | grep "tag_name" | sed -E 's/.*"v([^"]+)".*/\1/')
          echo "::set-output name=runner_version::${RUNNER_VERSION}"
        id: extract_branch_name

  build-docker-build:
    uses: jmmirand-work/shared-workflows/.github/workflows/build-docker-amd64.yaml@main
    with: 
 #    tags: jmmirand/gha-docker-runner:${{ steps.extract_branch_name.outputs.runner_version }}
      tags: jmmirand/gha-docker-runner:2.291.1
      build_options: RUNNER_VERSION=2.291.1
    secrets:
      docker_user:  ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
