name: Build gha runner

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

jobs:
  push_to_registries:
    name: Push Docker image to multiple arch in registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files


      - name: Print docker arquitectures
        run: |
          docker buildx create --use

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub amd64
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          tags: jmmirand/gha-docker-runner
          push: true
