name: Clean Runs and Logs Workflows

on: [push]

jobs:
  call-workflow-clean-workflows-logs:
    uses: jmmirand-work/shared-workflows/.github/workflows/clean-workflows-runs.yaml@main
    with:
      num_runs: 5
    secrets:
      myToken: ${{ secrets.GITHUB_TOKEN }}
